sudo: false
os:
  - linux
dist: trusty
language: python
python:
  - 3.6

addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - libblas-dev
      - liblapack-dev

script:
  - ./build-george.sh
  - ./plot-meghan.py data/MC.h5
